2.6. Разбивка на мелкие компоненты.
htmlacademy-vue/77699-pizza-1 pull request #3
Opened 2021-08-30 11:15 UTC by shuniada

2021-08-30 14:46 UTC, Djaler requested changes

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                <AppDrag v-bind:transfer-data="filling">
Нужно отключать перетаскивание при достижении максимального количества ингредиентов

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +          this.counterValue = this.counterValue + data.count;
теоретически так может быть превышено максимальное количество ингредиентов (если в data.count прилетит больше чем 1)

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
нехорошо, что этот базовый компонент что-то знает про filling и т.д.
Он должен быть абстрагирован от этого

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    Price() {
цену стоит рассчитывать с помощью computed

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    Price() {
в том числе и цену ингредиентов

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    Price() {
а ещё нужно умножать цену на модификатор размера

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +        this.Fillings.push(value);
нельзя мутировать проп напрямую, нужно бросать событие

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +      if (this.priceTotal > 350 && this.pizzaName.length > 0) {
мне кажется, тут не от цены нужно отталкиваться, а от наличия выбранных ингредиентов

2021-08-30 14:46 UTC, Djaler commented on src/frontend/src/common/components/SelectorItem.vue
> +  name: "SelectorItem",
по-моему, не очень подходящее имя для этого компонента. Selector подразумевает, что тут что-то выбирается. А что?

2021-08-31 05:49 UTC, shuniada commented on src/frontend/src/common/components/SelectorItem.vue
> +  name: "SelectorItem",
> по-моему, не очень подходящее имя для этого компонента. Selector подразумевает, что тут что-то выбирается. А что?

В задании было написано: SelectorItem.vue (для отображения картинки и текста справа).

2021-08-31 05:51 UTC, shuniada commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +      if (this.priceTotal > 350 && this.pizzaName.length > 0) {
> мне кажется, тут не от цены нужно отталкиваться, а от наличия выбранных ингредиентов

Но ведь наличие выбранных ингредиентов влияет и на цену, почему тогда по ней нельзя ориентироваться?

2021-08-31 06:04 UTC, Djaler commented on src/frontend/src/common/components/SelectorItem.vue
> +  name: "SelectorItem",
![Screenshot_20210831_090420](https://user-images.githubusercontent.com/7964583/131450531-f6eecbb8-5e2c-4de8-8dd5-1f7627978906.png)
Речь шла скорее про это, например

2021-08-31 06:05 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +      if (this.priceTotal > 350 && this.pizzaName.length > 0) {
Цена же приходит динамически. Если ингредиенты станут стоить дешевле, то может пицца вполне стоить дешевле 350)

2021-08-31 06:11 UTC, shuniada commented on src/frontend/src/common/components/SelectorItem.vue
> +  name: "SelectorItem",
так эти элементы слева расположены)

2021-08-31 06:12 UTC, shuniada commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +      if (this.priceTotal > 350 && this.pizzaName.length > 0) {
Ок, поняла

2021-08-31 06:13 UTC, Djaler commented on src/frontend/src/common/components/SelectorItem.vue
> +  name: "SelectorItem",
Не слева на странице. А `картинка и текст справа (от неё)`.

2021-08-31 06:26 UTC, shuniada commented on src/frontend/src/common/components/SelectorItem.vue
> +  name: "SelectorItem",
А, теперь понятно стало!

2021-08-31 07:28 UTC, Djaler commented on src/frontend/src/common/components/SelectorItem.vue
> +  name: "SelectorItem",
Ну и те компоненты, что в задании написаны, это просто пример, можно разбивать как хочешь

2021-08-31 07:50 UTC, shuniada commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
> нехорошо, что этот базовый компонент что-то знает про filling и т.д.
> Он должен быть абстрагирован от этого

А как без этого свойства определять какой именно ингредиент был добавлен?

2021-08-31 08:01 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
Это надо на уровень выше делать, там где ItemCounter используется

2021-09-01 07:03 UTC, shuniada commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
> Это надо на уровень выше делать, там где ItemCounter используется

А при перетаскивании ингредиента, счетчик каким образом следует обновлять? через Event Bus?

2021-09-01 07:05 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
Можно через eventbus, можно прокидывать событие через компонент просмотра пиццы

2021-09-01 07:52 UTC, shuniada commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
> Можно через eventbus

так а если убрать у ItemCounter параметр filling, то при событии из eventbus, все счетчики поменяют значение

2021-09-01 07:55 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
ItemCounter не должен общаться с eventbus. он должен своему родителю кидать событие с измененным количеством. В родителе ItemCounter'ы рисуются с помощью v-for по списку ингредиентов, поэтому при обработке события есть возможность получить информацию о том, для какого ингредиента изменилось значение

2021-09-01 08:00 UTC, shuniada commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
> поэтому при обработке события есть возможность получить информацию о том, для какого ингредиента изменилось значение

т.е. значение при перетаскивании ингредиента передавать через props в ItemCounter?

2021-09-01 08:03 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +    fillingName: {
Да, ItemCounter должен принимать prop с текущим значением. И кидать событие с измененным значением при нажатии на меньше/больше. Т.е., он максимально абстрагирован от того, что именно он считает.

2021-09-01 19:32 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      this.fillingsPrice = this.recountFillings;
не нужно сохранять результат расчета computed свойств. Можно же просто к ним обращаться где нужно

2021-09-01 19:33 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    recountFillings() {
имя computed свойства не должно быть глаголом. Потому что это свойство, а не метод

2021-09-01 19:38 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      this.fillingCounter = value.count;
много неиспользуемых полей осталось

2021-09-01 19:39 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      v-bind:Fillings="countFillings(Fillings)"
в качестве пропса передаётся результат вызова метода, у которого есть и сайд эффект (установка this.fillingsCount). это нехорошо. можно заменить этот метод на два computed-свойства

2021-09-02 06:20 UTC, shuniada commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      v-bind:Fillings="countFillings(Fillings)"
> в качестве пропса передаётся результат вызова метода, у которого есть и сайд эффект (установка this.fillingsCount). это нехорошо. можно заменить этот метод на два computed-свойства

т.е. надо, чтобы одно свойство возвращало массив ингредиентов, а второе - this.fillingsCount?

2021-09-02 07:23 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      v-bind:Fillings="countFillings(Fillings)"
Ну оно не должно прям возвращать this.fillingsCount. оно и должно им являться.
Т.е., вместо того чтобы дергать метод для пересчета fillingsCount - нужно сделать fillingsCount computed-свойством.

2021-09-02 07:24 UTC, shuniada commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      v-bind:Fillings="countFillings(Fillings)"
> Ну оно не должно прям возвращать this.fillingsCount. оно и должно им являться.
> Т.е., вместо того чтобы дергать метод для пересчета fillingsCount - нужно сделать fillingsCount computed-свойством.

ага, понятно

2021-09-02 07:28 UTC, merged