5.7. HTTP. Работа с сервером
htmlacademy-vue/77699-pizza-1 pull request #6
Opened 2021-11-22 14:56 UTC by shuniada

2021-11-22 19:20 UTC, Djaler commented
Запросы профиля (адреса, история заказа) делаются при открытии приложения даже неавторизированным пользователем, при этом выводится ошибка

2021-11-22 19:26 UTC, Djaler commented
Ошибка валидации пропа при выборе пункта "Новый адрес" в корзине

2021-11-22 19:27 UTC, Djaler commented
Ограничение на количество пицц и дополнительных товаров нужно убрать. В ТЗ было указано ограничение только про ингредиенты

2021-11-22 19:28 UTC, Djaler commented
Список адресов нужно обновлять при открытии соответствующей страницы. Иначе, получается не совсем очевидно:
1. Делаем заказ на новый адрес
2. Открываем страницу "Мои данные"
3. Не видим там этого адреса

2021-11-22 19:29 UTC, Djaler commented on src/frontend/src/modules/profile/components/ProfileNewAddress.vue
> +              v-model="name"
тут мутируется значение пропа, так делать нельзя, нужно явно бросать событие наверх

2021-11-22 19:30 UTC, Djaler commented on src/frontend/src/modules/profile/components/ProfileNewAddress.vue
> +              v-model="name"
![image](https://user-images.githubusercontent.com/7964583/142923393-2e0c4adf-53e6-458d-a168-29149e875806.png)

2021-11-22 19:33 UTC, Djaler commented on src/frontend/src/modules/profile/components/ProfileNewAddress.vue
> +        <button type="submit" class="button" v-on:click="addAddress">
Добавление адреса происходит дважды, так как тут есть и обработчик клика и обработчик отправки сабмита формы

2021-11-22 19:36 UTC, Djaler commented on src/frontend/src/App.vue
> +    this.$store.dispatch("Builder/getDoughs");
Хорошо бы сгруппировать экшены модуля Builder в один большой, который будет дергать остальные

2021-11-22 19:36 UTC, Djaler commented on src/frontend/src/common/components/PizzaFoundation.vue
> +        'pizza pizza--foundation--' +
лучше это вынести в computed

2021-11-22 19:38 UTC, Djaler commented on src/frontend/src/modules/profile/components/ProfileAddressItem.vue
> +              showAddressForm = !showAddressForm;
не стоит присваивания делать в шаблоне, лучше вынести в метод

2021-11-22 19:41 UTC, Djaler commented on src/frontend/src/layouts/AppLayout.vue
> +      const layout = this.isAuthenticated
В итоге не используются лейауты, указанные в meta. Лучше будет в одном компоненте объединить шаблоны для залогиненного пользователя и нет, через v-if

2021-11-22 19:42 UTC, Djaler commented on src/frontend/src/store/index.js
> +    [ADD_NOTIFICATION](state, notification) {
тут нет никакого состояния, можно это сделать не модулем стора, а сервисом, например

2021-11-22 19:44 UTC, Djaler commented on src/frontend/src/views/Cart.vue
> +        this.flat = addr.flat;
эти значения используются в шаблоне в v-model, но изначально в data не инициализированы, из-за этого происходят некоторые ошибки в консоли

2021-11-23 14:05 UTC, shuniada commented on src/frontend/src/modules/profile/components/ProfileNewAddress.vue
> +              v-model="name"
т.е. тут надо данные об адресе передавать не через проп?

2021-11-23 14:22 UTC, Djaler commented on src/frontend/src/modules/profile/components/ProfileNewAddress.vue
> +              v-model="name"
Я не про то. Я имею в виду, что когда в этом AppInput меняются данные, то благодаря связке через v-model меняется значение `name`. Но это не локальные данные компонента, а проп. Пропы нельзя менять изнутри компонента. Если тебе снаружи `ProfileNewAddress` эти данные не нужно менять, то просто сохрани данные, пришедшие в пропах, в data, и уже с ними работай

2021-11-23 14:24 UTC, shuniada commented on src/frontend/src/modules/profile/components/ProfileNewAddress.vue
> +              v-model="name"
а, хорошо!

2021-11-24 10:11 UTC, shuniada commented on src/frontend/src/store/index.js
> +    [ADD_NOTIFICATION](state, notification) {
т.е. из экшена вызывать метод сервиса или внести изменения в сам notifier.js и оттуда вызывать сервис?

2021-11-24 11:06 UTC, Djaler commented on src/frontend/src/store/index.js
> +    [ADD_NOTIFICATION](state, notification) {
Да можно вообще в самом notifier эти алерты держать и всё

2021-11-24 16:44 UTC, Djaler requested changes

2021-11-24 16:44 UTC, Djaler commented on src/frontend/src/App.vue
> +      this.$store.dispatch("Profile/getAddresses");
эти запросы лучше делать непосредственно при открытии соответствующих страниц. пользователь может даже до них не дойти, а данные мы всё равно тягаем

2021-11-24 16:44 UTC, Djaler commented on src/frontend/src/layouts/AppLayout.vue
> +  components: { AppLayoutDefault },
так все-таки, зачем убирать динамическое подключение лейаута? как раз отлично этот подход ложится на нашу ситуацию. добавляем новый лейаут для профиля - в нём будет хедер и сайдбар. не придется сайдбар дублировать на обоих страницах профиля

2021-11-24 16:44 UTC, Djaler commented on src/frontend/src/layouts/AppLayout.vue
> +  components: { AppLayoutDefault },
а хедер просто отдельным компонентом сделать, чтоб его в обоих лейаутах использовать

2021-11-24 16:44 UTC, Djaler commented on src/frontend/src/store/modules/builder.store.js
> +      const doughsData = await this.$api.dough.query(config);
тут запросы выполняются последовательно. хорошо бы выполнять параллельно, чтоб не ждать лишнее время

2021-11-24 16:44 UTC, Djaler commented on src/frontend/src/views/Cart.vue
> +        pizzaObj.push({
тут нужно либо использовать forEach вместо map, либо делать map правильно. Array.map позволяет получить новый массив из существующего, преобразовав каждый элемент. то есть, тебе нужно чтобы функция внутри map возвращала результат. И соответственно результатом map будет новый массив

2021-11-24 16:44 UTC, Djaler commented on src/frontend/src/views/Login.vue
> +    this.$refs.email.$refs.input.focus();
нехорошо так глубоко залазить внутрь дочернего компонента. Правильнее будет сделать у AppInput метод focus (в котором дёргать фокус нативного инпута), а тут дёргать этот метод.
А ещё лучше - сделать у AppInput проп `autofocus`, при установке которого компонент сам автоматически сделает фокус на инпуте

2021-11-25 08:14 UTC, shuniada commented on src/frontend/src/layouts/AppLayout.vue
> +  components: { AppLayoutDefault },
а что понимается под сайдбаром?

2021-11-25 08:16 UTC, Djaler commented on src/frontend/src/layouts/AppLayout.vue
> +  components: { AppLayoutDefault },
боковое меню (в котором ссылки на Истории заказов и Мои данные)

2021-11-25 09:42 UTC, shuniada commented on src/frontend/src/layouts/AppLayout.vue
> +  components: { AppLayoutDefault },
а я не совсем поняла, зачем добавлять новый лейаут для профиля, если можно объединить их в один шаблон, где через v-if отображать иконки для залогиненного пользователя и нет, а сайдбар отдельно вынести?

2021-11-25 09:44 UTC, Djaler commented on src/frontend/src/layouts/AppLayout.vue
> +  components: { AppLayoutDefault },
У нас страницы сейчас двух типов есть - на некоторых есть хедер, а на некоторых есть хедер и сайдбар. Вот это наши 2 лейаута

2021-11-26 06:44 UTC, merged